void displayInt(int toDisplay);
void intToArray(int * array, int number);
void resetAll(void);
void digitSelect(int* digitArray,int currentDigit );
void Display_Thread(void const *argument);
void start_display_thread(void);
void set_key_pressed_display(char c);
char get_key_pressed_display(void);
void initializeDisplayToZero(void);
void set_acc_value_display(float *temp_value);
void get_acc_value_display(float *temp_value);
int concatenateArray();
int concatenate(int x, int y);
void enterNumberIntoBuffer(int numberEntered);
void deleteLastInBuffer();
void user_pwm_set_led_brightness(uint16_t ld3, uint16_t ld4,uint16_t ld5,uint16_t ld6);
float calculatePitchAngleFromAccVals(float ax, float ay, float az);
float calculateRollAngleFromAccVals(float ax, float ay, float az);